name: Deploy to S3

on:
  pull_request:
    branches: 
      - master
    types: [closed]

jobs:
  deploy:
    if: ${{ github.event.pull_request.merged }}
    permissions:
      id-token: write
      contents: write
    name: Deploy
    environment: prod
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::087229364167:role/PortfolioRole
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Aws version
      run: aws --version
    - name: Deploy
      run: aws s3 sync . s3://${{ secrets.S3_BUCKET }}/
