name: Deploy to S3 for Static Host

on: workflow_dispatch

jobs:
  deploy:
    permissions:
      id-token: write
      contents: write
    name: Deploy
    environment: prod
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::087229364167:role/PortfolioRole
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Deploy to S3
      run: aws s3 sync . s3://${{ secrets.S3_BUCKET }}/
